# GitHub OAuth client secret
apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-secret
  namespace: educates-config
stringData:
  client-secret: "2865b721cfc0baa19f898456a72740dbf588b7f2"
---
# Voucher signing key (same key your frontend uses to sign JWTs)
apiVersion: v1
kind: Secret
metadata:
  name: voucher-signing-key
  namespace: educates-config
stringData:
  secret: "your-shared-secret-minimum-32-bytes"